YAP_CarRent/1.UI-2/Controllers/LoginController.cs
using _1.UI.Code;
using _1.UI_2.Models;
using _2.BL;
using _4.Entities;
using _4.Entities.Validation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace _3.SP_UI.Controllers
{
    public class LoginController : Controller
    {

        const string ERROR_LOGIN = "כתובת המייל או הסיסמה אינם נכונים";

        UserManager userManager;
        List<User> users;


        public LoginController()
        {
            userManager = new UserManager();
            users = userManager.Users;

        }

        // GET: Login

        public ActionResult Index()
        {
            if (!Request.IsAuthenticated)
            {
                //ViewBag.User = users[2];
                return View("Index", masterName: "_LayoutLogin");
            }
            else
                return RedirectToAction(SessionManager.LastPage[0], SessionManager.LastPage[1]);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginInfo loginInfo, string returnUrl)
        {
            var tempUser = users.Where(u => u.Email == loginInfo.Email && u.Password.Trim() == loginInfo.Password).FirstOrDefault();
            if (tempUser != null)
            {
                /* login succeeded !!! :) */
                LoginUser(tempUser);

                //return RedirectToAction(SessionManager.LastPage[0], SessionManager.LastPage[1]);
                if (string.IsNullOrEmpty(returnUrl))
                {
                    // redirect to the default page
                    //return RedirectToAction("Index","Home");
                    return RedirectToAction(SessionManager.LastPage[0], SessionManager.LastPage[1]);

                }
                else
                {
                    // redurect to the last requested page
                    return Redirect(returnUrl);
                }
            }
            else
                ViewBag.error = ERROR_LOGIN;
            return View("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginOld(LoginInfo loginInfo)
        {
            if (SessionManager.IsConnected)
            {

                var tempUser = users.Where(u => u.Email == loginInfo.Email && u.Password.Trim() == loginInfo.Password).FirstOrDefault();
                if (tempUser != null)
                {
                    SessionManager.User = tempUser;
                   var b= HttpContext.User.IsInRole("dddd");
                    ViewBag.b = b;
                }
                else
                {

                    ViewBag.error = ERROR_LOGIN;
                    ViewBag.email = loginInfo.Email;
                    return View("Index", masterName: "_LayoutLogin");
                }

            }
            else
            {
                SessionManager.LastPage = new List<string>() { "Index", "Home" };

            }
            // Redirect to the last page the user was
            return RedirectToAction(SessionManager.LastPage[0], SessionManager.LastPage[1]);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {

            FormsAuthentication.SignOut(); // remove the authentication cookie

            Session.Abandon(); // close the Session for the specific user



            return RedirectToAction(SessionManager.LastPage[0], SessionManager.LastPage[1]);

        }

        [ValidateAntiForgeryToken]
        public ActionResult Register()
        {




            return View("Register", masterName: "_LayoutLogin");


        }

        [ValidateAntiForgeryToken]
        public ActionResult RegisterNewUser(User user)
        {
            if (ModelState.IsValid)
            {
               
                userManager.RegisterNewUser(user);
                user.Roles.Add(userManager.Roles.Where(r => r.Name == "User").FirstOrDefault());
                userManager.AddRolesToUser(user, user.Roles.ToList());
                LoginUser(user);
                return RedirectToAction(SessionManager.LastPage[0], SessionManager.LastPage[1]);
            }
            else
            {
                string errors = "";
                foreach (var value in ModelState.Values)
                {
                    foreach (var er in value.Errors)
                    {
                        errors += errors + er.ErrorMessage + "<br/>";
                    }
                }
                ViewBag.errors = errors;
                return View("Register", masterName: "_LayoutLogin");
            }







        }


        //
        private bool IsPassword(User user, string password)
        {
            if (user.Password == password)
                return true;
            return false;
        }

        public JsonResult TZ(int tz)
        {

            return Json(new TZAttribute().IsValid(tz), JsonRequestBehavior.AllowGet);


        }

        public JsonResult Email(string _email)
        {
            var _tempUser = userManager.Users.Where(e => e.Email == _email).FirstOrDefault();

            return Json(_tempUser!=null, JsonRequestBehavior.AllowGet);


        }

        private void LoginUser(User _user)
        {
            _user.LastEntryDTime = DateTime.Now;
            // save the user identity in a cookie & session
            FormsAuthentication.SetAuthCookie(_user.Email, false);
            SessionManager.User = _user;
            userManager.UpdateLogin(_user);
        }
    }
}

YAP_CarRent/1.UI-2/Controllers/OrdersController.cs
using _1.UI.Code;
using _1.UI_2.Models;
using _2.BL;
using _4.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1.UI_2.Controllers
{
    [Authorize(Roles = "User,Employee,Manager")]
    public class OrdersController : Controller
    {
        CarManager carManager;
        OrderManager orderManager;
        BranchManager branchManager;
        public OrdersController()
        {
            orderManager = new OrderManager();
            carManager = new CarManager();
        }
        // GET: Orders

        public ActionResult Index()
        {
            //var b1 = User.IsInRole("Employee,Manager");
            //var b2 = User.IsInRole("User");
            if (!User.IsInRole("Employee"))
            {
                ViewBag.User = GetUserFromSession();
            }
            //var b3 = User.IsInRole("Employee");

            return View();
        }

        public ActionResult GetAllUsers()
        {

            List<User> users;
            if (User.IsInRole("Employee"))
            {
                users = orderManager.GetAllUser();
            }
            else
            {
                users = new List<_4.Entities.User>() { SessionManager.User };
            }
            return Json(users, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Return(int id)
        {

            Order order = orderManager.Orders.Where(o => o.ID == id).FirstOrDefault();
            Model model = carManager.Models.Where(m => m.ID == order.Car.Model).FirstOrDefault();
            OrderVM vm = new OrderVM()
            {
                User = order.User1.FirstName,
                Car = order.Car.Serial,
                Branch = new BranchManager().Branches.Where(b => b.ID == order.Branch).Select(b => b.Name).FirstOrDefault(),
                Image = order.Car.Image,
                From = order.StartDate.ToString("dd/MM/yy"),
                To = order.EndDate.ToString("dd/MM/yy"),
                Return = DateTime.Now.ToString("dd/MM/yy"),
                Price = model.Group.PerDay * (order.EndDate - order.StartDate).Days,
                Fine = model.Group.DayFine * (DateTime.Now - order.EndDate).Days,
                ID = id
                
            };
            return View(vm);
        }

        [Authorize(Roles = "Employee")]
        [ValidateAntiForgeryToken]
        public ActionResult CloseOrder(int id, string _returnDate)
        {
            if (Request.IsAuthenticated)
            {
                DateTime returnDate = DateTime.Parse(_returnDate.Split('/')[1] + "/" + _returnDate.Split('/')[0] + "/" + _returnDate.Split('/')[2]);
                var order = orderManager.Orders.Where(o => o.ID == id).FirstOrDefault();
                order.ReturnDate = returnDate;
                bool b = orderManager.CloseOreder(order);

                if (b)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Return", id);
                }
            }
            else
                return RedirectToAction("Index");
            
        }

        public ActionResult Order(int _carNumber)
        {
            var car = carManager.Cars.Where(c => c.Serial == _carNumber).FirstOrDefault();
            OrderVM vm = new OrderVM()
            {
                Car = car.Serial,
                Branch = new BranchManager().Branches.Where(b => b.ID == car.Branch).Select(b => b.Name).FirstOrDefault(),
                Image = car.Image,
                Price = carManager.Models.Where(m => m.ID == car.Model).Select(p => p.Group.PerDay).FirstOrDefault()

            };

            return View(vm);
        }

        [ValidateAntiForgeryToken]
        public ActionResult Create(string _from, string _to, int _carNumber, string _branch)
        {
            Order order = new Order()
            {
                StartDate = Convert.ToDateTime(_from),
                EndDate = Convert.ToDateTime(_to),
                User = SessionManager.User.ID != 0 ? SessionManager.User.ID : new UserManager().GetUserByEmail(SessionManager.User.Email).ID,
                Branch = new BranchManager().Branches.Where(b => b.Name == _branch).Select(b => b.ID).FirstOrDefault(),
                IsActive = true,
                CarNumber = _carNumber



            };
            var IsOrder = orderManager.Create(order);

            /*
           V ID -- V
           V User - Session V
           V StartDate - request
           V EndDate - request
           X ReturnDate --
           V CarNumber -request
           V IsActive - true
           V Branch - request
           */

            return RedirectToAction("Index");
        }
        
        public JsonResult GetAllOrders(int TZ)
        {

            List<Order> orders= orderManager.Orders.Where(o => o.User1.TZ == TZ).ToList();
            if (User.IsInRole("Employee"))
            {
                orders = orderManager.Orders.Where(o=>o.User1.TZ==TZ).ToList();
            }
            else
            {
                var user = GetUserFromSession();
            }
           
            

            return Json(OrdersVM(orders), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCurrent()
        {
            User user;
            if (!User.IsInRole("Employee"))
            {
                user = GetUserFromSession();
            }
            else
            {
                user = null;
            }
            return Json(user,JsonRequestBehavior.AllowGet);
        }

        private List<OrderVM> OrdersVM(List<Order> orders)
        {

            branchManager = new BranchManager();
            var ordersVM = new List<OrderVM>();
            foreach (var order in orders)
            {
                string returnDate = order.ReturnDate != null ? ((DateTime)order.ReturnDate).ToString("dd/MM/yy") : "תהנה מהרגע";
                var model = carManager.Models.Where(m => m.ID == order.Car.Model).FirstOrDefault();
                ordersVM.Add(
               new OrderVM()
               {
                   Branch = branchManager.Branches.Where(b => b.ID == order.Branch).FirstOrDefault().Name,
                   Car = order.Car.Serial,
                   From = ((DateTime)order.StartDate).ToString("dd/MM/yy"),
                   ID = order.ID,
                   Model = model.Name,
                   //  Price = carManager.Models.Where(m => m.ID == order.Car.Model).FirstOrDefault().Group.PerDay * (order.EndDate - order.StartDate).Days,
                   Price = model.Group.PerDay * (order.EndDate - order.StartDate).Days,
                   To = ((DateTime)order.EndDate).ToString("dd/MM/yy"),
                   Return = returnDate,
                   User = order.User1.FirstName











               });
            }
            return ordersVM;
        }

        /// <summary>
        /// Privets get null
        /// </summary>
        /// <returns></returns>
        private User GetUserFromSession()
        {
            User user = SessionManager.User.ID != 0 ? SessionManager.User : new UserManager().GetUserByEmail(SessionManager.User.Email);
            user.Roles = null;
            return user;
        }

        public JsonResult IsCarAvailable(int car,string _from,string _to)
        {
            bool b;
            try
            {
                b = orderManager.IsCarAvailable(car, Convert.ToDateTime(_from), Convert.ToDateTime(_to));
            }
            catch (Exception)
            {

                b = false;
            }
            return Json(b,JsonRequestBehavior.AllowGet);

        }

    }
}

YAP_CarRent/1.UI-2/Controllers/UsersController.cs
using _1.UI_2.Models;
using _2.BL;
using _4.Entities;
using _4.Entities.Validation;
using _4.Entities.ExtentionMethods;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1.UI_2.Controllers
{
    [Authorize(Roles = "Manager,Admin")]
    public class UsersController : Controller
    {
        UserManager manager;
        public UsersController()
        {
            manager = new UserManager();
        }
        // GET: Users
        public ActionResult Index()
        {
            return View("Manage");
        }

        public ActionResult Create()
        {
            var vm = InitEditUserVM(new User());
            return View(vm);
        }

        public ActionResult Create(User _user)
        {
            if (Request.IsAuthenticated)
            {
                _user.Roles = SetNewRoles(_user);
                if (manager.RegisterNewUser(_user))
                    return View("Index");
                else
                {
                    return View();
                }
            }
            return View();
        }

        public ActionResult Manage()
        {
            // ManageUsersVM mangaeVM = new ManageUsersVM(manager.Users, manager.Roles, 10);
            return View();
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            var user = manager.Users.Where(u => u.ID == ID).FirstOrDefault();
            var editUserVM = InitEditUserVM(user);
            return View(editUserVM);
        }
        [HttpPost]
        public ActionResult Edit(User _user)
        {
            if (Request.IsAuthenticated)
            {
                bool b = manager.EditUser(_user);
                bool b1 = manager.AddRolesToUser(_user, SetNewRoles(_user));
                manager.Dispose();
                if (b && b1)
                    return RedirectToAction("Manage");
                else
                    return Edit(_user.ID);
            }
            else
            {

                var editUserVM = InitEditUserVM(_user);
                return View(editUserVM);
            }
        }

        public ActionResult InitPage(int perPage)
        {
            var users = manager.Users.Take(perPage).ToList();

            var initPage = new ManageUsersVM(users, manager.Roles, perPage);
            return Json(initPage, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ToPage(int perPage, int from)
        {


            return Json(manager.Users.Skip(from).Take(perPage).ToList(), JsonRequestBehavior.AllowGet);
        }

        private EditUserVM InitEditUserVM(User _user)
        {


            var _userroles = _user.Roles.ToList();
            var _roles2 = manager.Roles.Where(r => !_userroles.Contains(r)).ToList();
            EditUserVM editUserVM = new EditUserVM() { User = _user, Roles2 = _roles2 };
            return editUserVM;
        }


        public JsonResult TZ(int tz)
        {

            return Json(new TZAttribute().IsValid(tz), JsonRequestBehavior.AllowGet);


        }

        private List<Role> SetNewRoles(User _user)
        {
            List<User> _users = new List<_4.Entities.User>() { _user };
            var userRoles = _user.UserRoles.Split(',');
            List<Role> newRoles = manager.Roles.Where(r => userRoles.Contains(r.Name)).Select(r => new Role() { ID = r.ID, Name = r.Name, Users = _users }).ToList();
            //_user.Roles = newRoles;
            return newRoles;
        }

    }

}

YAP_CarRent/1.UI-2/Views/Shared/AutoDa.cshtml
<h1 class="ya-autoDa-font h1" id="autoda-left"><span style="color:black">Auto</span><span style="color:red">Da</span></h1>

YAP_CarRent/1.UI-2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>AutoDa</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />

    <!-- GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Hind:300,400,500,600,700" rel="stylesheet" type="text/css">
    <link href="~/asentus/vendor/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/asentus/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- PAGE LEVEL PLUGIN STYLES -->
    <link href="~/asentus/css/animate.css" rel="stylesheet">
    <link href="~/asentus/vendor/swiper/css/swiper.min.css" rel="stylesheet" type="text/css" />

    <!-- THEME STYLES -->
    <link href="~/asentus/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico" />
</head>
<body dir="rtl">
    <!--========== HEADER ==========-->
    <header class="header navbar-fixed-top">
        <!-- Navbar -->
        <nav class="navbar" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="menu-container">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="toggle-icon"></span>
                    </button>

                    <!-- Logo -->
                    <div class="col-xs-2">
                        <a style="text-decoration:none" href="/Home/Index">@Html.Partial("~/Views/Shared/AutoDa.cshtml")</a>
                    </div>



                    <!-- End Logo -->
                    <div class="col-xs-4 margin-l-5">@Html.Partial("~/Views/Shared/_LoginPartial.cshtml")</div>
                </div>


                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse nav-collapse">
                    <div class="menu-container">
                        <ul class="navbar-nav navbar-nav-right">


                            <li class="nav-item">@Html.ActionLink("בית", "Index", "Home", "", new { @class = "nav-item-child nav-item-hover active" })</li>
                            <li class="nav-item">@Html.ActionLink("מכוניות", "Index", "Cars", "", new { @class = "nav-item-child nav-item-hover" })</li>
                            <li class="nav-item">@Html.ActionLink("עלינו", "About", "Home", "", new { @class = "nav-item-child nav-item-hover" })</li>
                           @if (User.IsInRole("User"))
                           {
                            <li class="nav-item">@Html.ActionLink("ההזמנות שלי", "Index", "Orders", "", new { @class = "nav-item-child nav-item-hover" })</li>

                           }
                             @if (User.IsInRole("Manager"))
                            {
                                <li class="nav-item">

                                    <a class="dropdown-toggle nav-item-child nav-item-hover"
                                       data-toggle="dropdown"
                                       href="#">
                                        ניהול מלאי
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <!-- links -->
                                        <li class="nav-item">@Html.ActionLink("רשימת מכוניות", "Manage", "Cars", "", new { @class = "" })</li>
                                        <li class="nav-item">@Html.ActionLink("הוסף מכונית", "Create", "Cars", "", new { @class = "" })</li>

                                    </ul>


                                </li>
                                <li class="nav-item">

                                    <a class="dropdown-toggle nav-item-child nav-item-hover"
                                       data-toggle="dropdown"
                                       href="#">
                                        ניהול משתמשים
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <!-- links -->
                                        <li class="nav-item">@Html.ActionLink("הוסף עובד", "Create", "Users", "", new { @class = "" })</li>
                                        <li class="nav-item">@Html.ActionLink("ניהול משתמשים", "Manage", "Users", "", new { @class = "" })</li>

                                    </ul>


                                </li>



                            }




                            <li class="nav-item"></li>



                        </ul>
                    </div>
                </div>
                <!-- End Navbar Collapse -->
            </div>

        </nav>
        <!-- Navbar -->

    </header>
    <!--========== END HEADER ==========-->




    <div class="container body-content">
        @RenderBody()


       

        <a href="javascript:void(0);" class="js-back-to-top back-to-top">Top</a>
    </div>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link href="~/css/Shared/layout.css" rel="stylesheet" />

    <!-- JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- CORE PLUGINS -->
    <script src="~/asentus/vendor/jquery.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/jquery-migrate.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

    <!-- PAGE LEVEL PLUGINS -->
    <script src="~/asentus/vendor/jquery.easing.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/jquery.back-to-top.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/jquery.smooth-scroll.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/jquery.wow.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/swiper/js/swiper.jquery.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/masonry/jquery.masonry.pkgd.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/masonry/imagesloaded.pkgd.min.js" type="text/javascript"></script>

    <!-- PAGE LEVEL SCRIPTS -->
    <script src="~/asentus/js/layout.min.js" type="text/javascript"></script>
    <script src="~/asentus/js/components/wow.min.js" type="text/javascript"></script>
    <script src="~/asentus/js/components/swiper.min.js" type="text/javascript"></script>
    <script src="~/asentus/js/components/masonry.min.js" type="text/javascript"></script>

    <link href="~/css/Login/Index.css" rel="stylesheet" />
    @RenderSection("Scripts", required: false)
</body>
</html>

YAP_CarRent/1.UI-2/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>AutoDa</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />

    <!-- GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Hind:300,400,500,600,700" rel="stylesheet" type="text/css">
    <link href="~/asentus/vendor/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/asentus/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- PAGE LEVEL PLUGIN STYLES -->
    <link href="~/asentus/css/animate.css" rel="stylesheet">
    <link href="~/asentus/vendor/swiper/css/swiper.min.css" rel="stylesheet" type="text/css" />

    <!-- THEME STYLES -->
    <link href="~/asentus/css/layout.min.css" rel="stylesheet" type="text/css" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico" />
</head>
<body dir="rtl">
    <!--========== HEADER ==========-->
    <header class="header navbar-fixed-top">
        <!-- Navbar -->
        <nav class="navbar" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="menu-container">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="toggle-icon"></span>
                    </button>

                    <!-- Logo -->
                    <div class="col-xs-2">
                        <a style="text-decoration:none" href="/Home/Index">@Html.Partial("~/Views/Shared/AutoDa.cshtml")</a>
                    </div>



                    <!-- End Logo -->
                    @*<div class="col-xs-4 margin-l-5">@Html.Partial("~/Views/Shared/_LoginPartial.cshtml")</div>*@
                </div>


                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse nav-collapse">
                    <div class="menu-container">
                        <ul class="navbar-nav navbar-nav-right">

                      
                            <li class="nav-item">@Html.ActionLink("בית", "Index", "Home", new { @class = "nav-item-child nav-item-hover active" })</li>
                            <li class="nav-item">@Html.ActionLink("מכוניות", "Index", "Cars", new { @class = "nav-item-child nav-item-hover" })</li>
                            <li class="nav-item">@Html.ActionLink("עלינו", "About", "", new { @class = "nav-item-child nav-item-hover" })</li>
                            <li class="nav-item"></li>



                        </ul>
                    </div>
                </div>
                <!-- End Navbar Collapse -->
            </div>

        </nav>
        <!-- Navbar -->

    </header>
    <!--========== END HEADER ==========-->




    <div class="container body-content">
        @RenderBody()


        <hr />
        <!--========== FOOTER ==========-->
      
        <!--========== END FOOTER ==========-->
        <a href="javascript:void(0);" class="js-back-to-top back-to-top">Top</a>
    </div>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link href="~/css/Shared/layout.css" rel="stylesheet" />

    <!-- JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- CORE PLUGINS -->
    <script src="~/asentus/vendor/jquery.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/jquery-migrate.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

    <!-- PAGE LEVEL PLUGINS -->
    <script src="~/asentus/vendor/jquery.easing.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/jquery.back-to-top.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/jquery.smooth-scroll.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/jquery.wow.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/swiper/js/swiper.jquery.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/masonry/jquery.masonry.pkgd.min.js" type="text/javascript"></script>
    <script src="~/asentus/vendor/masonry/imagesloaded.pkgd.min.js" type="text/javascript"></script>

    <!-- PAGE LEVEL SCRIPTS -->
    <script src="~/asentus/js/layout.min.js" type="text/javascript"></script>
    <script src="~/asentus/js/components/wow.min.js" type="text/javascript"></script>
    <script src="~/asentus/js/components/swiper.min.js" type="text/javascript"></script>
    <script src="~/asentus/js/components/masonry.min.js" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

YAP_CarRent/1.UI-2/Views/Shared/_LoginPartial - Copy.cshtml
@using _4.Entities
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">
            <li>
                <p>"שלום @ViewBag.User.FirstName"</p>
            </li>
            <li><a href="javascript:document.getElementById('logoutForm').submit()">התנתק</a></li>
        </ul>
    }
}
else
{
    using (Html.BeginForm("Index", "Login", FormMethod.Get, new { id = "loginForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
      
    }
    <form action="/Login/Index" method="post">

        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">

            <li><input type="submit" class="nav-item-child nav-item-hover" value="כניסה"/></li>
        </ul>

    </form>
    using (Html.BeginForm("Register", "Login", FormMethod.Get, new { id = "registerForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
        <ul class="nav navbar-nav navbar-right">
            @*<li><a href="/Login/Register" id="registerLink" class="nav-item-child nav-item-hover">הרשמה</a></li>*@
            <li><a href="javascript:document.getElementById('registerForm').submit()" class="nav-item-child nav-item-hover">הרשמה</a></li>
        </ul>
    }





    @*<li>@Html.ActionLink("הירשם", "Register", "Login", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink("התחבר", "Login", "Login", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>*@

}